version: '3.8'
services:
  gamerverse:
    image: gamerverse:latest
    container_name: gamerverse
    restart: unless-stopped
    tty: true
    networks: 
      - mynet
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "443:443"
    volumes:
       - ./nginx/conf.d/:/etc/nginx/conf.d/
       - ./nginx/ssl/:/etc/nginx/ssl/
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
